apiVersion: 1

groups:
  - orgId: 1
    name: fawkes-availability
    folder: alerts
    interval: 30m
    rules:
      - uid: fawkes_down_alert
        title: Fawkes Host Down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus-nimbus
            model:
              datasource:
                type: prometheus
                uid: prometheus-nimbus
              expr: up{instance="fawkes:9100"}
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: Alerting
        execErrState: Alerting
        for: 30m
        annotations:
          description: Fawkes host has been unreachable for over 5 minutes
        labels: {}
        isPaused: false
        notification_settings:
          receiver: homeassistant
