apiVersion: 1

groups:
  - name: syncoid-backup
    orgId: 1
    folder: alerts
    interval: 30m
    rules:
      - uid: syncoid_failure_alert
        title: Syncoid Backup Failed
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus-nimbus
            model:
              datasource:
                type: prometheus
                uid: prometheus-nimbus
              expr: node_systemd_unit_state{name="syncoid-tank.timer", state="failed"} == 1 or node_systemd_unit_state{name="syncoid-tank.service", state="failed"} == 1
              instant: true
              refId: A
        for: 5m
        noDataState: OK
        execErrState: Alerting
        labels:
          receiver: homeassistant
        annotations:
          description: Syncoid backup timer or service has failed
      - uid: syncoid_overdue_alert
        title: Syncoid Backup Overdue
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 90000
              to: 0
            datasourceUid: prometheus-nimbus
            model:
              datasource:
                type: prometheus
                uid: prometheus-nimbus
              expr: (time() - node_systemd_timer_last_trigger_seconds{name="syncoid-tank.timer"}) > 86400
              instant: true
              refId: A
        for: 30m
        noDataState: OK
        execErrState: Alerting
        labels:
          receiver: homeassistant
        annotations:
          description: Syncoid backup hasn't run in over 24 hours
